### ISSUE TITLE
What day is it??

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#117]
The date displayed by our DateStr component is a day behind our DateInput component.

I assume the issue is realted to UTC vs local time, and the fact that the DateInput does not have a time portion of the date-time, which is interpreted at midnight (UTC?).

All displayed/inputed dates and times should be local time.

**Comment by sudhacheran** [comment]
Issue is due to UTC Vs local time. I have tried splitting the date and use  "new Date(yyyy, mm, dd)". It fixed the issue.
