### ISSUE TITLE
Create reusable template parts

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#119]
We seem to be using the same content for parts of each workflow template. Namely, the Project tab and the beginning of the Report tab.  One of the beauties of MDX it produces a React component. So we should be able to create reusable parts of templates.

These template parts should live in _reusable_ folder inside the _templates_ folder.
Say we create a template part in _templates/reusable/project_info_inputs.mdx_ called that includes the mdx for the Project tab.
Then in _components/mdx_wrapper.tsx_ we add the line `import ProjectInfoInputs from "../templates/reusable/project_info_inputs.mdx` and add `ProjectInfoInputs` to the `components` object.
Then we can use `<ProjectInfoInputs />` in the Project tab of our workflow templates.

**Comment by sudhacheran** [comment]
Charile, I have tried my implementing as you have detailed. ProjectInfoInputs importing this way is imported as JSX element. So the component inside ProjectInfoInputs such as 'StringInput' is not getting initialized. So app is throwing error saying 'StringInput' not found.

**Comment by charliepnnl** [comment]
@sudhacheran Try using `<ProjectInfoInputs {...props} />`.
The `{...props}` sends all the properties on to ProjectInfoInputs; that should include `components`.

**Comment by sudhacheran** [comment]
Committed the changes to the brach "119-create-reusable-template-parts".
