### ISSUE TITLE
Improve Add/Rename Project Name modal

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#139]
- [ ] The Add button in the modal for adding or renaming a project name should be disabled if the input is invalid. See ![Screen Shot 2023-08-04 at 12 42 03 PM](https://github.com/pnnl/Quality-Install-Tool/assets/72275714/16da2f84-c973-4f8b-858e-2a5662abe32d)
- [ ] The error message should be <small>, possibly italic, and red.
- [ ] The validation should be run on each keystroke if the string is non-empty.
- [ ] The input should receive focus when the modal opens.

**Comment by sudhacheran** [comment]
This issue is fixed
