### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#16]
Turn on offline support. This should be one of the last features to implement since it makes testing slightly more difficult.

This will at least involve:
- [ ] In `/index.tsx` change `unregister()` to `register()`.

**Comment by ssuds** [comment]
Hey @charliepnnl! Curious if this is still on the roadmap? Would be a great value feature to have. I see it was previously marked as low priority so I was wondering if you anticipate it being implemented anytime soon
