### ISSUE TITLE
Attachment metadata should only be store in doc.metadata_...

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#162]
Currently attachment metadata is being stored in two places:
- In `doc.metadata_.attachments[*]
- In the store state variable `attachments[*].metadata`

This is potentially confusing and error prone. 
I would like to eliminate `attachments[*].metadata`.
This has several ramifications:
- The form of the `attachments` store state variable can be simplified to `attachments = {[id]: blog, ...}`.
  - Any code that uses the `attachments` variable will need to be updated accordingly.
- Any component wrapper that uses attachment metadata will need to pull `metadata` from `StoreContext.Consumer`.

**Comment by sudhacheran** [comment]
DB structure has been changed and metadata is now stored appropriately.
