### ISSUE TITLE
Functionality for downloading and uploading project-level installation details

### ISSUE THREAD

**Issue by sudhacde** [pnnl/Quality-Install-Tool#186]
Provide users with an option to download/upload project-level installation details to Quality Install Tool from their device.
1. **Download Functionality(Save Project Details Locally):** Add option for the user to Download/Save the project doc locally in their device as a JSON file. The JSON file should include all the necessary information about the project's installation details, including data, metadata and attachments.
2. **Upload Functionality:** Allow users to upload previously saved/shared project installation JSON file to the Tool. After uploading, the file will be processed, and the project details will be added to the tool.

**Comment by charliepnnl** [comment]
I don't think we can save all the project data, including attachments, in a JSON file. I believe the doc (JSON) and attachments will need to be put into some sort of zip file.
