### ISSUE TITLE
Update workflow template content

### ISSUE THREAD

**Issue by sudhacheran** [pnnl/Quality-Install-Tool#238]
"Quality Install Tool Edit Requests Nov 14 2024" - Changes requested by Edward

**Comment by lindsayJohnstonPnnl** [comment]
[Quality Install Tool Workflow Edits Request Nov 14 2024.docx](https://github.com/user-attachments/files/17998548/Quality.Install.Tool.Workflow.Edits.Request.Nov.14.2024.docx)

**Comment by lindsayJohnstonPnnl** [comment]
Might need to add a `<NumericalDisplay/>` component that can be used to round numbers, then use that to round the calculations to one decimal place in this ticket.
