### ISSUE TITLE
Gas workflows template updates

### ISSUE THREAD

**Issue by sudhacheran** [pnnl/Quality-Install-Tool#245]
The following changes need to be applied to the respective templates

High Efficiency Gas Furnace
Manometer Showing ~Inlet~ Outlet Gas pressure – Photo
Take a photo of the manometer measuring the ~inlet~ outlet gas pressure for single, two, and three speed gas furnaces. Skip this photo prompt if the furnace is a modulating firing rate furnaces.
 
High Efficiency Water Heater – remove the photo prompt below, the reason is most of the units purchased will be modulating firing rate tankless water heaters.
Manometer Showing Inlet Gas pressure – Photo
Take a photo of the manometer measuring the inlet gas pressure.
 
High Efficiency Modulating Boiler – remove the photo prompt below, the reason is modulating firing rate equipment have a computer controlled gas valve to adjust the outlet pressure for the given firing rate.
Manometer Showing Inlet Gas pressure – Photo
Take a photo of the manometer measuring the inlet gas pressure.

**Comment by lindsayJohnstonPnnl** [comment]
![image](https://github.com/user-attachments/assets/6078d2dc-e018-4b50-997c-22d97e4b4400)
