### ISSUE TITLE
Create new web app logo and color styling

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#50]
The current logo is a simple "QA" with a green background.

Since the name of the web app is now "Quality Install Tool", perhaps "QI" would be more appropriate?  Other ideas for the logo are welcome.

Also, take a look at the general styling of the BASC where the web app will reside. Consider what color(s) might be more appropriate for the logo, and possible for the web app itself.

**Comment by RaeChen07** [comment]
![IMG_0558](https://github.com/pnnl/Remote-QA-Web-App/assets/44009406/5a7f4f17-f553-47b4-89d8-31e423eb56f6)

**Comment by charliepnnl** [comment]
Use https://realfavicongenerator.net/ to generate the favicon and related images needed for a web app.  The directions there explain where the various files need to go. This is what I used to generate the current favicon, etc.

My suspicion is that the words at the bottom won't scale down well.  I believe the smallest icon it generates is 16x16 pixels.

**Comment by charliepnnl** [comment]
Looks awesome BTW!
