### ISSUE TITLE
Follow software dependency licenses

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#70]
We need to make sure we are following the licensing requirements of our dependencies.

This webpack plugin may be helpful: https://www.npmjs.com/package/webpack-license-plugin

**Comment by sudhacheran** [comment]
- I have used "license-checker" from https://www.npmjs.com/package/license-checker. Below is the summary of licenses used in our linking libraries. 
- Verifying with https://spdx.org/licenses/, to see if it has any distribution restriction.

├─ MIT: 1242
├─ ISC: 59
├─ CC0-1.0: 43
├─ BSD-2-Clause: 37
├─ Apache-2.0: 36
├─ BSD-3-Clause: 28
├─ BSD: 10
├─ Unlicense: 3
├─ (MIT OR CC0-1.0): 3
├─ 0BSD: 2
├─ BSD-3-Clause OR MIT: 1
├─ Python-2.0: 1
├─ MPL-2.0: 1
├─ CC-BY-4.0: 1
├─ (Apache-2.0 OR MPL-1.1): 1
├─ (AFL-2.1 OR BSD-3-Clause): 1
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ MIT*: 1
├─ UNLICENSED: 1
├─ BSD*: 1
├─ (WTFPL OR MIT): 1
├─ CC-BY-3.0: 1
└─ (MIT AND CC-BY-3.0): 1
