### ISSUE TITLE
Scope of Service Worker & LocalStorage

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#73]
The scope of both the ServiceWorker & LocalStorage is the origin (https://developer.mozilla.org/en-US/docs/Glossary/Origin) of the loading page. This is a real problem for our GithubPages deployment since the origin is pnnl.github.io.  In other words, our web app could interfere with any other web app deployed from pnnl.github.io.  Aack!

Anyone that forks our repo and uses the GithubPages deployment will have a similar issue.

I see two viable options:
1. We move our repo to a non-pnnl github repository. I _think_ this would give us our own domain to work with: user_name.github.io.
2. We use a custom domain.

**Comment by jackcruz53** [comment]
A custom domain would be an expense that I think is very justifiable in this context. I think moving the repo may require us to setup things we have already set up; where as a custom domain is a guaranteed and flexible solution.
