### ISSUE TITLE
Request Geolocation Permissions

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Quality-Install-Tool#94]

**Comment by RaeChen07** [comment]
on my Android phone
 - Take a Photo do give GeoLocation
 - Chose a photo from album (where the photo do have a geolocation) does not give a goelocation.

**Comment by charliepnnl** [comment]
@RaeChen07  What is your phone model and android version?

Mine is a Pixel 4a running Android version 13. I am able to get photos from the camera or gallery with geolocation set.

**Comment by RaeChen07** [comment]
samsung Galaxy Z flip 4, version 13 too

**Comment by charliepnnl** [comment]
The post, https://stackoverflow.com/questions/16297730/image-upload-from-iphone-strips-exif-data, is a bit more than two years old, but consistent with what we have seen. Apparently, iOS always strips the geolocation from all photos it passes to a browser.

My proposal:
- We attempt to get the timestamp and geolocation from the image. Put this in an object of the form `{geolocation, timestamp}`.
- If the image has a timestamp but not a geolocation, we fill the geolocation field with the current GPS geolocation. We also store the current time in an additional `geo_timestamp` field. 
- Store the created object in the document's metadata_ field.
- Store the attachment.
